; ESP32-S3-LCD-1.3 (Waveshare) — Robô Holográfico
; ST7789 240x240 SPI, ESP32-S3R8 (8MB octal PSRAM), 16MB flash, QMI8658 IMU

[env:esp32-s3-lcd-13]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DLGFX_USE_V1
    -Wall
    -std=gnu++17
build_unflags =
    -std=gnu++11

lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    bitbank2/AnimatedGIF@^2.1.1
    bodmer/TJpg_Decoder@^1.1.0
    bblanchon/ArduinoJson@^7.2.0

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
